ASANAS = [
  {
    title: 'Anahatasana (Melting Heart)',
    benefits: 'A nice backbend for the upper and middle back. Opens the shoulders. Softens the heart.',
    contraindications: 'If you have a bad neck, this could strain it. Be aware of any tingling in the hands or fingers, which may indicate nerve compression.',
    into_pose: 'On your hands and knees, walk your hands forward, allowing your chest to drop toward the floor. Keep your hips above your knees.',
    alternatives_and_options: 'If shoulder pain prevents arms from going overhead, move them further apart. Use a bolster under the chest for support. Try one arm at a time.',
    out_of_pose: 'Move back into Child\'s Pose or slide forward onto your belly.',
    counterposes: 'Child\'s Pose or lying on your stomach.',
    meridians_and_organs: 'Stimulates the Urinary Bladder, Heart, Lung, Stomach, and Spleen meridians.',
    joints: 'Compression for the upper back. Mild stress on the lower spine and shoulder joints.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Upward-Facing Dog.',
    other_notes: 'Carefully monitor sensations in the neck, especially if resting the chin on the floor.'
  },
  {
    title: 'Ankle Stretch',
    benefits: 'Stretches the ankles and the top of the feet.',
    contraindications: 'Avoid if you have knee pain or ankle injuries.',
    into_pose: 'Sit back on your heels with toes untucked.',
    alternatives_and_options: 'Place a blanket under the knees or shins for support.',
    out_of_pose: 'Lean forward onto your hands and release the legs.',
    counterposes: 'Point and flex the feet.',
    meridians_and_organs: 'Stomach and Spleen meridians.',
    joints: 'Ankles and knees.',
    recommended_time: 'Two to four minutes.',
    similar_yang_asanas: 'Hero Pose.',
    other_notes: 'This pose helps improve ankle flexibility.'
  },
  {
    title: 'Bananasana',
    benefits: 'Stretches the side body and spine. Opens the intercostal muscles.',
    contraindications: 'Avoid if you have lumbar spine injuries.',
    into_pose: 'Lie on your back, reach arms overhead, and bend the body into a banana shape.',
    alternatives_and_options: 'Use a bolster for support along the side.',
    out_of_pose: 'Slowly return to a neutral position.',
    counterposes: 'Supine Twist or Savasana.',
    meridians_and_organs: 'Stimulates Gallbladder and Liver meridians.',
    joints: 'Spine and shoulders.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Extended Side Angle Pose.',
    other_notes: 'Great for improving lateral flexibility.'
  },
  {
    title: 'Butterfly',
    benefits: 'Stretches the inner thighs, hips, and lower back.',
    contraindications: 'Avoid deep forward folds if you have sciatica or lumbar issues.',
    into_pose: 'Sit with soles of the feet together and allow knees to drop outward.',
    alternatives_and_options: 'Place blocks under the knees for support.',
    out_of_pose: 'Use your hands to support yourself back to a seated position.',
    counterposes: 'Seated Twist or lying flat.',
    meridians_and_organs: 'Stimulates Kidney, Liver, and Urinary Bladder meridians.',
    joints: 'Hips and lower spine.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Bound Angle Pose.',
    other_notes: 'This pose helps open the hips for meditation.'
  },
  {
    title: 'Half Butterfly',
    benefits: 'Stretches one side of the lower back and inner thighs.',
    contraindications: 'Avoid if you have lumbar disc injuries.',
    into_pose: 'Extend one leg forward and bend the other foot to the inner thigh.',
    alternatives_and_options: 'Use a bolster under the bent knee.',
    out_of_pose: 'Support yourself back to a seated position.',
    counterposes: 'Cat-Cow Stretch.',
    meridians_and_organs: 'Kidney and Liver meridians.',
    joints: 'Hips and lower spine.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Janu Sirsasana.',
    other_notes: 'Focus on relaxing the spine as you fold.'
  },
  {
    title: 'Camel',
    benefits: 'Opens the chest, shoulders, and stretches the hip flexors.',
    contraindications: 'Avoid if you have severe neck or lower back pain.',
    into_pose: 'Kneel on the floor and lean back to place hands on heels.',
    alternatives_and_options: 'Place hands on blocks next to the feet for support.',
    out_of_pose: 'Slowly return to an upright kneeling position.',
    counterposes: 'Child\'s Pose.',
    meridians_and_organs: 'Stimulates Heart and Lung meridians.',
    joints: 'Spine and shoulders.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Wheel Pose.',
    other_notes: 'Focus on opening the heart and avoiding lower back compression.'
  },
  {
    title: 'Cat Pulling Its Tail',
    benefits: 'Stretches the shoulders, spine, and hips.',
    contraindications: 'Avoid if you have wrist or knee injuries.',
    into_pose: 'On hands and knees, thread one arm through the other and pull the shoulder toward the floor.',
    alternatives_and_options: 'Place a bolster under the chest for more support.',
    out_of_pose: 'Return to all fours slowly.',
    counterposes: 'Child\'s Pose.',
    meridians_and_organs: 'Stimulates the Gallbladder and Liver meridians.',
    joints: 'Shoulders, spine, and hips.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Thread the Needle Pose.',
    other_notes: 'Great for relieving tension in the upper back.'
  },
  {
    title: 'Caterpillar',
    benefits: 'Stretches the spine, hamstrings, and relieves lower back tension.',
    contraindications: 'Avoid if you have spinal disc issues.',
    into_pose: 'Sit with legs extended and slowly fold forward, bringing the chest toward the thighs.',
    alternatives_and_options: 'Place a cushion under the knees for support.',
    out_of_pose: 'Slowly uncurl the spine to return to seated position.',
    counterposes: 'Seated Twist.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Spine and hamstrings.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Seated Forward Fold.',
    other_notes: 'Keep the spine long to avoid strain.'
  },
  {
    title: 'Child\'s Pose',
    benefits: 'Gently stretches the back and hips, calming the nervous system.',
    contraindications: 'Avoid if you have knee injuries.',
    into_pose: 'Kneel and sit on the heels, then fold forward with arms extended.',
    alternatives_and_options: 'Place a cushion under the chest for added support.',
    out_of_pose: 'Slowly lift back up into kneeling position.',
    counterposes: 'Cat-Cow Stretch.',
    meridians_and_organs: 'Stimulates the Kidney meridians.',
    joints: 'Knees, hips, and spine.',
    recommended_time: 'Two to five minutes.',
    similar_yang_asanas: 'Balasana.',
    other_notes: 'Focus on releasing tension in the spine and pelvis.'
  },
  {
    title: 'Dangling',
    benefits: 'Relieves tension in the spine, neck, and hamstrings.',
    contraindications: 'Avoid if you have neck or lower back injuries.',
    into_pose: 'Stand with feet hip-width apart, then bend forward and let your head hang.',
    alternatives_and_options: 'Bend the knees slightly if hamstrings are tight.',
    out_of_pose: 'Slowly roll up one vertebra at a time.',
    counterposes: 'Standing Tall or Tadasana.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Spine and hips.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Forward Fold.',
    other_notes: 'Keep the knees soft to avoid straining the lower back.'
  },
  {
    title: 'Deer Pose',
    benefits: 'Opens the hips and stretches the quadriceps.',
    contraindications: 'Avoid if you have knee or hip injuries.',
    into_pose: 'Sit with legs extended, then bend one knee and place the foot near the opposite hip.',
    alternatives_and_options: 'Use a cushion for support under the hip of the bent leg.',
    out_of_pose: 'Return to seated position and switch sides.',
    counterposes: 'Reclined Twist.',
    meridians_and_organs: 'Stimulates the Liver and Gallbladder meridians.',
    joints: 'Hips and knees.',
    recommended_time: 'Two to five minutes per side.',
    similar_yang_asanas: 'Lotus Pose.',
    other_notes: 'Helps improve hip flexibility and mobility.'
  },
  {
    title: 'Dragons',
    benefits: 'Deeply stretches the hips, quads, and hip flexors.',
    contraindications: 'Avoid if you have knee or hip injuries.',
    into_pose: 'Step one foot forward into a lunge, keeping the back leg extended.',
    alternatives_and_options: 'Place blocks under the hands for added stability.',
    out_of_pose: 'Slowly step back into a standing position.',
    counterposes: 'Child\'s Pose.',
    meridians_and_organs: 'Stimulates the Liver, Spleen, and Kidney meridians.',
    joints: 'Hips, knees, and spine.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Lunge Pose.',
    other_notes: 'Hold each side to feel a deep stretch in the hip flexors.'
  },
  {
    title: 'Frog',
    benefits: 'Deeply stretches the inner thighs, groin, and hips.',
    contraindications: 'Avoid if you have knee issues or hip pain.',
    into_pose: 'Start on all fours, then widen the knees and bring the feet to face outward.',
    alternatives_and_options: 'Place cushions under the knees for comfort.',
    out_of_pose: 'Move back into Child\'s Pose to relax.',
    counterposes: 'Child\'s Pose or seated forward fold.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Hips, knees, and pelvis.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Wide-Legged Forward Fold.',
    other_notes: 'This is a very deep stretch; use props to make it more accessible.'
  },
  {
    title: 'Happy Baby',
    benefits: 'Opens the hips and stretches the lower back.',
    contraindications: 'Avoid if you have neck or back issues.',
    into_pose: 'Lie on your back, grab the outside of your feet with your hands, and bring your knees toward your armpits.',
    alternatives_and_options: "Use a strap around the feet if you can't reach them.",
    out_of_pose: 'Release the feet and return to a lying position.',
    counterposes: 'Supta Baddha Konasana.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, spine, and knees.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Supta Padangusthasana.',
    other_notes: 'Focus on relaxing the neck and shoulders.'
  },
  {
    title: 'Reclining Twist',
    benefits: 'Relieves tension in the back and spine.',
    contraindications: 'Avoid if you have spinal issues or disc herniation.',
    into_pose: 'Lie on your back with knees bent, then slowly drop them to one side while turning your head in the opposite direction.',
    alternatives_and_options: 'Use a bolster under the knees for added support.',
    out_of_pose: 'Return to center and repeat on the other side.',
    counterposes: 'Savasana.',
    meridians_and_organs: 'Stimulates the Spleen and Stomach meridians.',
    joints: 'Spine and hips.',
    recommended_time: 'One to three minutes per side.',
    similar_yang_asanas: 'Seated Spinal Twist.',
    other_notes: 'Keep the shoulders grounded to deepen the twist.'
  },
  {
    title: 'Saddle',
    benefits: 'Opens the front of the hips and stretches the thighs.',
    contraindications: 'Avoid if you have knee or hip injuries.',
    into_pose: 'Kneel with knees wide apart, then lower your hips toward the floor and lie back on your forearms.',
    alternatives_and_options: 'Place cushions under the back for support if needed.',
    out_of_pose: 'Slowly sit up and return to a kneeling position.',
    counterposes: 'Child\'s Pose.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, knees, and spine.',
    recommended_time: 'Two to three minutes.',
    similar_yang_asanas: 'Camel Pose.',
    other_notes: 'This is an intense hip opener, so use props for support.'
  },
  {
    title: 'Shavasana',
    benefits: 'Calms the body and mind, reduces stress, and improves relaxation.',
    contraindications: 'None unless you have severe back issues.',
    into_pose: 'Lie on your back with arms at your sides, palms facing up. Close your eyes and focus on deep breathing.',
    alternatives_and_options: 'Use a bolster under the knees for added comfort if you have lower back pain.',
    out_of_pose: 'Slowly awaken the body by gently moving the fingers and toes.',
    counterposes: 'None needed, as this is a final resting pose.',
    meridians_and_organs: 'Stimulates the entire body, allowing the nervous system to relax.',
    joints: 'Entire body.',
    recommended_time: 'Five to ten minutes.',
    similar_yang_asanas: 'None.',
    other_notes: 'Focus on the breath and let go of all tension.'
  },
  {
    title: 'Shoelace',
    benefits: 'Stretches the hips and glutes while relieving tension in the lower back.',
    contraindications: 'Avoid if you have knee injuries or severe hip pain.',
    into_pose: 'Sit with your legs crossed and stack one knee on top of the other, bringing the feet to the sides of the body.',
    alternatives_and_options: 'Place a cushion under the hips for added comfort.',
    out_of_pose: 'Slowly uncross the legs and extend them forward.',
    counterposes: 'Seated Forward Fold.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, knees, and lower back.',
    recommended_time: 'One to three minutes per side.',
    similar_yang_asanas: 'Fire Log Pose.',
    other_notes: 'This is a deep stretch for the hips, so move slowly into it.'
  },
  {
    title: 'Snail',
    benefits: 'Stimulates the nervous system and improves circulation to the head.',
    contraindications: 'Avoid if you have neck or back injuries.',
    into_pose: 'Lie on your back and bring the legs over the head to the floor, using your arms to support the back.',
    alternatives_and_options: 'Use a block or cushion under the feet for added support.',
    out_of_pose: 'Slowly roll back to a seated position.',
    counterposes: 'Child\'s Pose.',
    meridians_and_organs: 'Stimulates the thyroid and nervous system.',
    joints: 'Spine and neck.',
    recommended_time: 'One to two minutes.',
    similar_yang_asanas: 'Plow Pose.',
    other_notes: 'This is an inversion, so proceed with caution.'
  },
  {
    title: 'Sphinx and Seal',
    benefits: 'Opens the chest and improves spinal flexibility.',
    contraindications: 'Avoid if you have severe lower back pain.',
    into_pose: 'Lie on your stomach, prop yourself up on your elbows for Sphinx Pose, and press into the hands to deepen the backbend for Seal Pose.',
    alternatives_and_options: 'Use a cushion under the pelvis if you have back discomfort.',
    out_of_pose: 'Slowly lower the torso to the floor.',
    counterposes: 'Child\'s Pose or Downward Dog.',
    meridians_and_organs: 'Stimulates the Heart and Lung meridians.',
    joints: 'Spine and shoulders.',
    recommended_time: 'Two to three minutes.',
    similar_yang_asanas: 'Cobra Pose.',
    other_notes: 'Ensure you\'re not overextending your lower back.'
  },
  {
    title: 'Square',
    benefits: 'Opens the hips and relieves tension in the lower back.',
    contraindications: 'Avoid if you have knee or hip issues.',
    into_pose: 'Sit with one leg bent in front and the other stacked on top, feet flexed and knees pointing out to the sides.',
    alternatives_and_options: 'Use cushions under the knees for support.',
    out_of_pose: 'Uncross the legs and return to a seated position.',
    counterposes: 'Child\'s Pose.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Hips and knees.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Seated Forward Fold.',
    other_notes: 'Keep the spine long while folding forward.'
  },
  {
    title: 'Squat',
    benefits: 'Stretches the hips, groin, and ankles.',
    contraindications: 'Avoid if you have knee or hip issues.',
    into_pose: 'Squat with feet flat on the floor, keeping the chest lifted and hands in prayer position.',
    alternatives_and_options: 'Place a block under the hips for support if needed.',
    out_of_pose: 'Slowly rise back into a standing position.',
    counterposes: 'Forward Fold or Child\'s Pose.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, knees, and ankles.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Malasana.',
    other_notes: 'This pose is great for building strength and flexibility in the lower body.'
  },
  {
    title: 'Straddle (Dragonfly)',
    benefits: 'Stretches the inner thighs and hamstrings, improving flexibility in the spine.',
    contraindications: 'Avoid if you have hamstring injuries.',
    into_pose: 'Sit with legs extended wide apart, then slowly fold forward, reaching for your feet or the floor.',
    alternatives_and_options: 'Use blocks under the hands for support.',
    out_of_pose: 'Slowly come up from the fold and return to seated position.',
    counterposes: 'Seated Forward Fold.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Spine, hips, and hamstrings.',
    recommended_time: 'Two to four minutes.',
    similar_yang_asanas: 'Wide-Legged Forward Fold.',
    other_notes: 'Focus on lengthening the spine during the fold.'
  },
  {
    title: 'Swan & Sleeping Swan',
    benefits: 'Opens the hips and stretches the quads, releasing tension in the lower back.',
    contraindications: 'Avoid if you have knee or hip pain.',
    into_pose: 'From Downward Dog, bring one knee toward the chest and extend the opposite leg behind.',
    alternatives_and_options: 'Use props under the hips for support.',
    out_of_pose: 'Slowly transition back to Child\'s Pose.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Hips and spine.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Pigeon Pose.',
    other_notes: 'This is a deep hip opener that should be approached with care.'
  },
  {
    title: 'Toe Squat',
    benefits: 'Stretches the feet, ankles, and shins.',
    contraindications: 'Avoid if you have ankle or knee injuries.',
    into_pose: 'Start kneeling, then tuck your toes under and sit back on your heels.',
    alternatives_and_options: 'Use a blanket under the knees for added support.',
    out_of_pose: 'Slowly release the feet and return to a seated position.',
    counterposes: 'Seated Forward Fold.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Ankles and knees.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Hero Pose.',
    other_notes: 'This pose can be intense for the feet, so proceed with caution.'
  },
  {
    title: 'Bridge (Supported Bridge)',
    benefits: 'Opens the chest and creates gentle spinal extension. Stretches hip flexors and strengthens the back.',
    contraindications: 'Avoid if you have hip replacements, arthritic hips, or severe low back issues. Not recommended for pregnant women.',
    into_pose: 'Lie on back with knees bent. Lift hips and slide block or bolster under pelvis/sacrum, NOT under low back.',
    alternatives_and_options: 'Straighten legs for deeper stretch. Raise arms overhead for more intensity. Use bolster under legs for gentler version.',
    out_of_pose: 'Come out slowly. Bend knees, lift hips slightly, remove support, then lower hips gently.',
    counterposes: 'Hug knees to chest to counteract the spinal extension.',
    meridians_and_organs: 'Stimulates Kidney, Urinary Bladder, Spleen, Stomach, Heart, and Lung meridians.',
    joints: 'Spine, hips, and shoulders.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Bridge Pose (Setubandha Sarvangasana).',
    other_notes: 'Great preparation for deeper backbends. Props allow for passive holding over longer periods.'
  },
  {
    title: 'Seal',
    benefits: 'Creates deeper spinal extension than Sphinx. Opens chest and stimulates lower back compression.',
    contraindications: 'Avoid if you have lower back injuries, disc problems, or neck issues. Not suitable for pregnancy.',
    into_pose: 'From Sphinx, straighten arms fully, hands wider than shoulders. Keep hips heavy on ground.',
    alternatives_and_options: 'Use blocks under hands for support. Keep hands wider apart if shoulders are tight.',
    out_of_pose: 'Lower to forearms first, then lie flat on stomach. Turn head to one side.',
    counterposes: 'Child\'s Pose or rest on stomach with head turned to side.',
    meridians_and_organs: 'Stimulates Kidney and Urinary Bladder meridians. Benefits sacral-lumbar arch.',
    joints: 'Spine, shoulders, and sacrum.',
    recommended_time: 'Two to five minutes.',
    similar_yang_asanas: 'Cobra Pose.',
    other_notes: 'Deeper backbend than Sphinx. Focus on keeping hips grounded and releasing muscular effort.'
  },
  {
    title: 'Half Saddle',
    benefits: 'Stretches quadriceps and hip flexors on one side. More accessible than full Saddle pose.',
    contraindications: 'Avoid if you have knee injuries, ankle problems, or severe lower back issues.',
    into_pose: 'Sit with one leg extended forward, other leg bent beside hip. Lean back on hands, then elbows if comfortable.',
    alternatives_and_options: 'Place cushion under bent knee. Use bolster behind back for support. Can fold forward over straight leg.',
    out_of_pose: 'Come up slowly to hands, then straighten bent leg carefully.',
    counterposes: 'Child\'s Pose or gentle forward fold to release lower back.',
    meridians_and_organs: 'Stimulates Kidney, Urinary Bladder, Stomach, and Spleen meridians.',
    joints: 'Hip flexors, quadriceps, lower spine, and knee.',
    recommended_time: 'Two to five minutes per side.',
    similar_yang_asanas: 'Reclined Hero Pose variation.',
    other_notes: 'Great preparation for full Saddle. Allows asymmetrical opening and easier modifications.'
  },
  {
    title: 'Winged Dragon',
    benefits: 'Deep hip flexor stretch with added chest opening. Combines Dragon with backbend.',
    contraindications: 'Avoid if you have knee, hip, or lower back injuries. Be cautious with shoulder issues.',
    into_pose: 'From Dragon pose, lift torso and place hands on front thigh. Open chest and lift heart.',
    alternatives_and_options: 'Keep hands on blocks or floor for less intensity. Can add gentle twist.',
    out_of_pose: 'Lower hands back to floor, step back to Downward Dog.',
    counterposes: 'Child\'s Pose or gentle forward fold.',
    meridians_and_organs: 'Stimulates Kidney, Liver, Heart, and Lung meridians.',
    joints: 'Hip flexors, spine, shoulders, and chest.',
    recommended_time: 'One to three minutes per side.',
    similar_yang_asanas: 'Low Lunge with chest opening.',
    other_notes: 'Advanced Dragon variation. Focus on opening heart while maintaining hip flexor stretch.'
  }
]

FLOWS = [
  {
    name: "An Easy Beginner's Flow",
    asanas: [
      { name: 'Opening Meditation', duration: 180, counterpose: '' },
      { name: 'Butterfly', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 180, counterpose: '' },
      { name: 'Straddle', duration: 90, counterpose: 'Windshield Wipers', instruction: 'Right leg forward' },
      { name: 'Straddle', duration: 90, counterpose: 'Windshield Wipers', instruction: 'Left leg forward' },
      { name: "Child's pose", duration: 60, counterpose: '' },
      { name: 'Sphinx', duration: 180, counterpose: '' },
      { name: 'Seal', duration: 180, counterpose: '' },
      { name: "Child's pose", duration: 60, counterpose: '' },
      { name: 'Half Shoelace', duration: 90, counterpose: 'Windshield Wipers',
        instruction: 'Left knee on top' },
      { name: 'Half Shoelace', duration: 90, counterpose: 'Windshield Wipers',
        instruction: 'Right knee on top' },
      { name: 'Happy Baby', duration: 180, counterpose: '' },
      { name: 'Reclining twist (left & right)', duration: 180, counterpose: '' },
      { name: 'Shavasana', duration: 180, counterpose: '' },
      { name: 'Finishing Meditation', duration: 180, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Spine (60min)',
    asanas: [
      { name: 'Opening Meditation', duration: 180, counterpose: '' },
      { name: 'Butterfly', duration: 240, counterpose: 'Winshield Wipers' },
      { name: 'Half Butterfly', duration: 240, counterpose: 'Windshield Wipers',
        instruction: 'Fold over left' },
      { name: 'Half Butterfly', duration: 240, counterpose: 'Windshield Wipers', instruction: 'Fold over right' },
      { name: 'Sphinx', duration: 240,
        counterpose: 'Relax on stomach, turn head to one side, and draw that knee up beside you on the floor' },
      { name: 'Sphinx', duration: 240,
        counterpose: 'Relax on stomach, turn head to the other side, and draw that knee up beside you on the floor' },
      { name: 'Bananasana', duration: 240, counterpose: 'Hug knees to chest and circle them',
        instruction: 'To right side' },
      { name: 'Bananasana', duration: 240, counterpose: 'Hug knees to chest and circle them',
        instruction: 'To left side' },
      { name: 'Reclining twist', duration: 240, counterpose: 'Hug knees to chest and circle them',
        instruction: 'Twist over right side' },
      { name: 'Reclining twist', duration: 240, counterpose: 'Hug knees to chest and circle them',
        instruction: 'Twist over left side' },
      { name: 'Shavasana', duration: 420 }
    ]
  },
  {
    name: 'A Flow for the Spine (90min)',
    asanas: [
      { name: 'Opening Meditation', duration: 300, counterpose: '' },
      { name: 'Dangling', duration: 180, counterpose: '' },
      { name: 'Squat', duration: 120, counterpose: '' },
      { name: 'Dangling', duration: 180, counterpose: '' },
      { name: 'Squat', duration: 120, counterpose: '' },
      { name: 'Straddle', duration: 180, counterpose: '' },
      { name: 'Straddle with side-bend (right)', duration: 120, counterpose: '' },
      { name: 'Straddle (left)', duration: 180, counterpose: '' },
      { name: 'Straddle with side-bend (left)', duration: 120, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 120, counterpose: '' },
      { name: 'Snail', duration: 180, counterpose: 'Tabletop' },
      { name: 'Sphinx', duration: 300,
        counterpose: 'Relax on stomach, turn head to one side, and draw that knee up beside you on the floor' },
      { name: 'Seal', duration: 300,
        counterpose: 'Relax on stomach, turn head to the other side, and draw that knee up beside you on the floor' },
      { name: 'Bananasana (to right)', duration: 300, counterpose: '' },
      { name: 'Bananasana (to left)', duration: 300, counterpose: 'Hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 600 }
    ]
  },
  {
    name: 'A Flow for the Hips (60min)',
    asanas: [
      { name: 'Meditation', duration: 180, counterpose: '' },
      { name: 'Butterfly', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Straddle', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 180, counterpose: 'Tabletop' },
      { name: 'Shoelace (right knee on top)', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Winged Dragon (right step forward)', duration: 120, counterpose: 'Step back to Down Dog' },
      { name: 'Shoelace (left knee on top)', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Winged Dragon (left step forward)', duration: 120, counterpose: 'Step back to Down Dog' },
      { name: 'Half Saddle (right leg forward)', duration: 180, counterpose: '' },
      { name: 'Half Saddle (left leg forward)', duration: 180, counterpose: "Child's Pose" },
      { name: 'Reclining Twist (Twisted Roots)', duration: 360, counterpose: 'Hug knees in and circle them' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Hips (90min)',
    asanas: [
      { name: 'Meditation', duration: 300, counterpose: '' },
      { name: 'Butterfly', duration: 300, counterpose: '' },
      { name: 'Straddle', duration: 600, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 180, counterpose: 'Tabletop' },
      { name: 'Shoelace (right knee on top)', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Dragon (right step forward)', duration: 180, counterpose: '' },
      { name: 'Winged Dragon (right step forward)', duration: 120, counterpose: 'Step back to Down Dog' },
      { name: 'Shoelace (left knee on top)', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Dragon (left step forward)', duration: 180, counterpose: '' },
      { name: 'Winged Dragon (left step forward)', duration: 120, counterpose: 'Step back to Down Dog' },
      { name: 'Camel (easy)', duration: 120, counterpose: '' },
      { name: 'Camel (deep)', duration: 120, counterpose: "Child's Pose" },
      { name: 'Saddle', duration: 300, counterpose: 'Crocodile' },
      { name: 'Reclining Twisted Roots (right side)', duration: 300, counterpose: '' },
      { name: 'Reclining Twisted Roots (left side)', duration: 300, counterpose: 'Hug knees in and circle them' },
      { name: 'Shavasana', duration: 600, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Legs (60min)',
    asanas: [
      { name: 'Meditation', duration: 180, counterpose: '' },
      { name: 'Butterfly', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Straddle', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 180, counterpose: 'Tabletop' },
      { name: 'Full Swan with right knee forward', duration: 120, counterpose: '' },
      { name: 'Sleeping Swan', duration: 120, counterpose: '' },
      { name: 'Shoelace with left knee on top', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Full Swan with left knee forward', duration: 120, counterpose: '' },
      { name: 'Sleeping Swan', duration: 120, counterpose: 'Windshield Wipers' },
      { name: 'Saddle, sitting between feet', duration: 180, counterpose: 'lie still with legs straight' },
      { name: 'Bananasana to the right', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Bananasana to the left', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Two-knee Reclining Twist on right side', duration: 60,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Two-knee Reclining Twist on left side', duration: 60,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Legs (90min)',
    asanas: [
      { name: 'Meditation', duration: 300, counterpose: '' },
      { name: 'Butterfly', duration: 300, counterpose: '' },
      { name: 'Straddle', duration: 600, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 300, counterpose: 'Tabletop' },
      { name: 'Full Swan with right knee forward', duration: 120, counterpose: '' },
      { name: 'Sleeping Swan', duration: 180, counterpose: '' },
      { name: 'Shoelace with left knee on top', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Full Swan with left knee forward', duration: 120, counterpose: '' },
      { name: 'Sleeping Swan', duration: 180, counterpose: '' },
      { name: 'Shoelace with right knee on top', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Saddle, sitting between feet', duration: 300, counterpose: 'lie still with legs straight' },
      { name: 'Bananasana to the right', duration: 300, counterpose: 'hug knees to chest and circle them' },
      { name: 'Bananasana to the left', duration: 300, counterpose: 'hug knees to chest and circle them' },
      { name: 'One-knee Reclining Twist on right side with top leg extended', duration: 180,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'One-knee Reclining Twist on left side with top leg extended', duration: 180,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 600, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Shoulders, Arms and Wrists (60min)',
    asanas: [
      { name: 'Child\'s Pose with arms overhead', duration: 180, counterpose: '' },
      { name: 'Anahatasana', duration: 180, counterpose: '' },
      { name: 'Sphinx', duration: 180, counterpose: 'relax on abdomen, turn head to one side' },
      { name: 'Seal', duration: 120, counterpose: '' },
      { name: 'Sphinx', duration: 180, counterpose: 'relax on abdomen, turn head to other side' },
      { name: 'Half Shoelace with right leg on top - Cowface Arms', duration: 120,
        counterpose: 'release arms and push hands apart', instruction: 'right hand behind back' },
      { name: 'Half Shoelace with right leg on top - Eagle Arms', duration: 120,
        counterpose: 'release arms and push hands apart', instruction: 'left arm under right' },
      { name: 'Stretch legs out straight and lean back on hands', duration: 60, counterpose: '' },
      { name: 'Half Shoelace with left leg on top - Cowface Arms', duration: 120,
        counterpose: 'release arms and push hands apart', instruction: 'left hand behind back' },
      { name: 'Half Shoelace with left leg on top - Eagle Arms', duration: 120,
        counterpose: 'release arms and push hands apart', instruction: 'right arm under left' },
      { name: 'Stretch legs out straight and lean back on hands', duration: 60, counterpose: '' },
      { name: 'Butterfly - Wrist stretch palms up', duration: 60, counterpose: 'shake out wrists' },
      { name: 'Butterfly - Wrist stretch palms down', duration: 60, counterpose: 'shake out wrists' },
      { name: 'Butterfly', duration: 180, counterpose: '' },
      { name: 'Two-knee Reclining Twist on right side with left arm alongside ear', duration: 120,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Two-knee Reclining Twist on left side with right arm alongside ear', duration: 120,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Shoulders, Arms and Wrists (90min)',
    asanas: [
      { name: 'Frog - Start in Tadpole', duration: 120, counterpose: '' },
      { name: 'Full Frog', duration: 180, counterpose: 'slide onto abdomen' },
      { name: 'Anahatasana', duration: 240, counterpose: '' },
      { name: 'Sphinx', duration: 300, counterpose: 'relax on abdomen, turn head to one side' },
      { name: 'Sphinx', duration: 180, counterpose: 'relax on abdomen, turn head to other side' },
      { name: 'Seal', duration: 120, counterpose: 'relax on abdomen, turn head to other side' },
      { name: 'Shoelace with right leg on top - Cowface Arms', duration: 180,
        counterpose: 'release arms and push hands apart', instruction: 'right hand behind back' },
      { name: 'Shoelace with right leg on top - Eagle Arms', duration: 120,
        counterpose: 'release arms and push hands apart', instruction: 'left arm under right' },
      { name: 'Sitting Swan with right ankle on left knee', duration: 120, counterpose: '',
        instruction: 'hands as far away as possible' },
      { name: 'Shoelace with left leg on top - Cowface Arms', duration: 180,
        counterpose: 'release arms and push hands apart', instruction: 'left hand behind back' },
      { name: 'Shoelace with left leg on top - Eagle Arms', duration: 120,
        counterpose: 'release arms and push hands apart', instruction: 'right arm under left' },
      { name: 'Sitting Swan with left ankle on right knee', duration: 120, counterpose: '',
        instruction: 'hands as far away as possible' },
      { name: 'Straddle - Wrist stretch palms up', duration: 120, counterpose: 'shake out wrists' },
      { name: 'Straddle - Wrist stretch palms down', duration: 120, counterpose: 'shake out wrists' },
      { name: 'Straddle', duration: 300, counterpose: '' },
      { name: 'One-knee Reclining Twist on right side with left arm alongside ear', duration: 300,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'One-knee Reclining Twist on left side with right arm alongside ear', duration: 300,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 600, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Kidney and Urinary Bladder Meridians (60min)',
    asanas: [
      { name: 'Sphinx', duration: 300, counterpose: 'relax on abdomen, turn head to the right' },
      { name: 'Saddle, sitting on feet or block', duration: 180, counterpose: 'Child\'s Pose' },
      { name: 'Sphinx', duration: 300, counterpose: 'relax on abdomen, turn head to the left' },
      { name: 'Butterfly', duration: 240, counterpose: '' },
      { name: 'Half Butterfly: fold over right leg', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Half Butterfly: fold over left leg', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Straddle fold straight down the middle', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 300, counterpose: 'Tabletop' },
      { name: 'Reclining Twist (Twisted Roots) - right side', duration: 240,
        counterpose: 'hug knees in and circle them' },
      { name: 'Reclining Twist (Twisted Roots) - left side', duration: 240,
        counterpose: 'hug knees in and circle them' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Kidney and Urinary Bladder Meridians (90min)',
    asanas: [
      { name: 'Sphinx', duration: 300, counterpose: 'relax on abdomen, turn head to the right' },
      { name: 'Saddle, sitting on feet or block', duration: 360, counterpose: 'Plank on elbows' },
      { name: 'Sphinx', duration: 180, counterpose: '' },
      { name: 'Seal', duration: 120, counterpose: 'relax on abdomen, turn head to the left' },
      { name: 'Butterfly', duration: 300, counterpose: '' },
      { name: 'Straddle fold over right leg', duration: 300, counterpose: '' },
      { name: 'Straddle fold over left leg', duration: 300, counterpose: '' },
      { name: 'Straddle fold straight down the middle', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Caterpillar', duration: 180, counterpose: '' },
      { name: 'Snail', duration: 120, counterpose: 'Tabletop' },
      { name: 'Anahatasana', duration: 240, counterpose: '' },
      { name: 'Dragon Cycle - right foot forward', duration: 300, counterpose: 'Down Dog',
        instruction: 'Baby Dragon 1min, High-Flying Dragon 2min, Winged Dragon 2min' },
      { name: 'Dragon Cycle - left foot forward', duration: 300, counterpose: 'Down Dog',
        instruction: 'Baby Dragon 1min, High-Flying Dragon 2min, Winged Dragon 2min' },
      { name: 'Reclining Twist (Twisted Roots) - right side', duration: 300,
        counterpose: 'hug knees in and circle them' },
      { name: 'Reclining Twist (Twisted Roots) - left side', duration: 300,
        counterpose: 'hug knees in and circle them' },
      { name: 'Shavasana', duration: 600, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Liver and Gall Bladder Meridians (60min)',
    asanas: [
      { name: 'Supported Bridge', duration: 180, counterpose: '' },
      { name: 'Sphinx', duration: 180, counterpose: 'relax on abdomen, turn head to a side' },
      { name: 'Sphinx', duration: 180, counterpose: '' },
      { name: 'Seal', duration: 120, counterpose: 'relax on abdomen, turn head to the left' },
      { name: 'Full Swan with right knee forward', duration: 60, counterpose: '' },
      { name: 'Sleeping Swan', duration: 180, counterpose: '' },
      { name: 'Child\'s Pose', duration: 60, counterpose: '' },
      { name: 'Shoelace with left knee on top', duration: 240, counterpose: 'Windshield Wipers',
        instruction: '2min twist left, 2min side bend left' },
      { name: 'Full Swan with left knee forward', duration: 60, counterpose: '' },
      { name: 'Sleeping Swan', duration: 180, counterpose: '' },
      { name: 'Child\'s Pose', duration: 60, counterpose: '' },
      { name: 'Shoelace with right knee on top', duration: 240, counterpose: 'Windshield Wipers',
        instruction: '2min twist right, 2min side bend right' },
      { name: 'Straddle fold over right leg', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Straddle fold over left leg', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Straddle fold straight down the middle', duration: 180, counterpose: 'Windshield Wipers' },
      { name: 'Bananasana to the right', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Bananasana to the left', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Two-knee Reclining Twist on right side', duration: 120,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Two-knee Reclining Twist on left side', duration: 120,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Liver and Gall Bladder Meridians (90min)',
    asanas: [
      { name: 'Supported Bridge', duration: 300, counterpose: '' },
      { name: 'Sphinx', duration: 300, counterpose: 'relax on abdomen, turn head to the right' },
      { name: 'Sphinx', duration: 180, counterpose: '' },
      { name: 'Seal', duration: 120, counterpose: 'relax on abdomen, turn head to the left' },
      { name: 'Full Swan with right knee forward', duration: 120, counterpose: '' },
      { name: 'Sleeping Swan', duration: 180, counterpose: '' },
      { name: 'Shoelace with left knee on top', duration: 300, counterpose: 'Windshield Wipers',
        instruction: '2min twist left, 3min side bend left' },
      { name: 'Full Swan with left knee forward', duration: 120, counterpose: '' },
      { name: 'Sleeping Swan', duration: 180, counterpose: '' },
      { name: 'Shoelace with right knee on top', duration: 300, counterpose: 'Windshield Wipers',
        instruction: '2min twist right, 3min side bend right' },
      { name: 'Straddle fold over right leg', duration: 300, counterpose: '',
        instruction: 'Add twisting/side bend halfway through' },
      { name: 'Straddle fold over left leg', duration: 300, counterpose: '',
        instruction: 'Add twisting/side bend halfway through' },
      { name: 'Straddle fold straight down the middle', duration: 300, counterpose: 'Windshield Wipers' },
      { name: 'Bananasana to the right', duration: 300, counterpose: 'hug knees to chest and circle them' },
      { name: 'Bananasana to the left', duration: 300, counterpose: 'hug knees to chest and circle them' },
      { name: 'One-knee Reclining Twist on right side with top leg extended', duration: 120, counterpose: '' },
      { name: 'One-knee twist with right knee bent', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'One-knee Reclining Twist on left side with top leg extended', duration: 180, counterpose: '' },
      { name: 'One-knee twist with left knee bent', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 600, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Stomach and Spleen Meridians (60min)',
    asanas: [
      { name: 'Child\'s Pose', duration: 180, counterpose: '' },
      { name: 'Supported Bridge', duration: 180, counterpose: '' },
      { name: 'Saddle, sitting on feet or block', duration: 240, counterpose: 'Child\'s Pose' },
      { name: 'Sphinx', duration: 180, counterpose: '' },
      { name: 'Seal', duration: 120, counterpose: 'relax on abdomen, turn head to a side' },
      { name: 'Shoelace with left knee on top', duration: 240, counterpose: 'Windshield Wipers',
        instruction: '2min twist left, 2min fold forward' },
      { name: 'Shoelace with right knee on top', duration: 240, counterpose: 'Windshield Wipers',
        instruction: '2min twist right, 2min fold forward' },
      { name: 'Caterpillar', duration: 180, counterpose: 'Tabletop' },
      { name: 'Dragon Cycle - right foot forward', duration: 240, counterpose: 'Down Dog',
        instruction: 'Baby Dragon 1min, Low-Flying Dragon 2min, Bowing Dragon 1min' },
      { name: 'Dragon Cycle - left foot forward', duration: 240, counterpose: 'Down Dog',
        instruction: 'Baby Dragon 1min, Low-Flying Dragon 2min, Bowing Dragon 1min' },
      { name: 'Two-knee Reclining Twist on right side', duration: 240,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Two-knee Reclining Twist on left side', duration: 240,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Stomach and Spleen Meridians (90min)',
    asanas: [
      { name: 'Child\'s Pose', duration: 300, counterpose: '' },
      { name: 'Supported Bridge', duration: 300, counterpose: '' },
      { name: 'Saddle, sitting on feet or block', duration: 360, counterpose: 'Plank on elbows' },
      { name: 'Shoelace with left knee on top', duration: 300, counterpose: 'Windshield Wipers',
        instruction: '2min twist left, 3min fold forward' },
      { name: 'Shoelace with right knee on top', duration: 300, counterpose: 'Windshield Wipers',
        instruction: '2min twist right, 3min fold forward' },
      { name: 'Caterpillar', duration: 180, counterpose: '' },
      { name: 'Snail', duration: 120, counterpose: 'Tabletop' },
      { name: 'Dragon Cycle - right foot forward', duration: 360, counterpose: 'Down Dog',
        instruction: 'Baby Dragon 2min, Low-Flying Dragon 2min, Dragon Splits 2min' },
      { name: 'Dragon Cycle - left foot forward', duration: 360, counterpose: 'Down Dog',
        instruction: 'Baby Dragon 2min, Low-Flying Dragon 2min, Dragon Splits 2min' },
      { name: 'One-knee Reclining Twist on right side', duration: 240, counterpose: '' },
      { name: 'One-knee Reclining Twist on left side', duration: 240,
        counterpose: 'hug knees to chest and circle them' },
      { name: 'Shavasana', duration: 600, counterpose: '' }
    ]
  },
  {
    name: 'A Flow for the Whole Body (60-75min)',
    asanas: [
      { name: 'Meditation', duration: 180, counterpose: '' },
      { name: 'Heart tapping', duration: 120, counterpose: '', instruction: 'Tap sternum with fingertips' },
      { name: 'Butterfly with Toes in Zipper', duration: 180, counterpose: '',
        instruction: 'Include neck circles and shoulder circles' },
      { name: 'Dangling', duration: 120, counterpose: '' },
      { name: 'Squat', duration: 120, counterpose: '' },
      { name: 'Toe Squat part 1', duration: 180, counterpose: '',
        instruction: 'Cowface Arms left hand behind, Eagle Arms right under, Face Yoga' },
      { name: 'Ankle Stretch', duration: 120, counterpose: 'Plank on elbows' },
      { name: 'Toe Squat part 2', duration: 180, counterpose: '',
        instruction: 'Cowface Arms right hand behind, Eagle Arms left under, Face Yoga' },
      { name: 'Ankle Stretch', duration: 120, counterpose: 'Plank on elbows' },
      { name: 'Sphinx', duration: 300, counterpose: 'Child\'s Pose' },
      { name: 'Happy Baby', duration: 180, counterpose: '' },
      { name: 'Bananasana to the right', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Bananasana to the left', duration: 180, counterpose: 'hug knees to chest and circle them' },
      { name: 'Reclining Twist (Twisted Roots) - right side', duration: 240, counterpose: '' },
      { name: 'Reclining Twist (Twisted Roots) - left side', duration: 240,
        counterpose: 'hug knees in and circle them' },
      { name: 'Tantrumasana', duration: 30, counterpose: '',
        instruction: 'Slap floor with hands and feet - 15sec, 10sec, 5sec bursts' },
      { name: 'Shavasana', duration: 420, counterpose: '' }
    ]
  }
]
