ASANAS = [
  {
    title: 'Anahatasana (Melting Heart)',
    benefits: 'A nice backbend for the upper and middle back. Opens the shoulders. Softens the heart.',
    contraindications: 'If you have a bad neck, this could strain it. Be aware of any tingling in the hands or fingers, which may indicate nerve compression.',
    into_pose: 'On your hands and knees, walk your hands forward, allowing your chest to drop toward the floor. Keep your hips above your knees.',
    alternatives_and_options: 'If shoulder pain prevents arms from going overhead, move them further apart. Use a bolster under the chest for support. Try one arm at a time.',
    out_of_pose: 'Move back into Child’s Pose or slide forward onto your belly.',
    counterposes: 'Child’s Pose or lying on your stomach.',
    meridians_and_organs: 'Stimulates the Urinary Bladder, Heart, Lung, Stomach, and Spleen meridians.',
    joints: 'Compression for the upper back. Mild stress on the lower spine and shoulder joints.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Upward-Facing Dog.',
    other_notes: 'Carefully monitor sensations in the neck, especially if resting the chin on the floor.'
  },
  {
    title: 'Ankle Stretch',
    benefits: 'Stretches the ankles and the top of the feet.',
    contraindications: 'Avoid if you have knee pain or ankle injuries.',
    into_pose: 'Sit back on your heels with toes untucked.',
    alternatives_and_options: 'Place a blanket under the knees or shins for support.',
    out_of_pose: 'Lean forward onto your hands and release the legs.',
    counterposes: 'Point and flex the feet.',
    meridians_and_organs: 'Stomach and Spleen meridians.',
    joints: 'Ankles and knees.',
    recommended_time: 'Two to four minutes.',
    similar_yang_asanas: 'Hero Pose.',
    other_notes: 'This pose helps improve ankle flexibility.'
  },
  {
    title: 'Bananasana',
    benefits: 'Stretches the side body and spine. Opens the intercostal muscles.',
    contraindications: 'Avoid if you have lumbar spine injuries.',
    into_pose: 'Lie on your back, reach arms overhead, and bend the body into a banana shape.',
    alternatives_and_options: 'Use a bolster for support along the side.',
    out_of_pose: 'Slowly return to a neutral position.',
    counterposes: 'Supine Twist or Savasana.',
    meridians_and_organs: 'Stimulates Gallbladder and Liver meridians.',
    joints: 'Spine and shoulders.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Extended Side Angle Pose.',
    other_notes: 'Great for improving lateral flexibility.'
  },
  {
    title: 'Butterfly',
    benefits: 'Stretches the inner thighs, hips, and lower back.',
    contraindications: 'Avoid deep forward folds if you have sciatica or lumbar issues.',
    into_pose: 'Sit with soles of the feet together and allow knees to drop outward.',
    alternatives_and_options: 'Place blocks under the knees for support.',
    out_of_pose: 'Use your hands to support yourself back to a seated position.',
    counterposes: 'Seated Twist or lying flat.',
    meridians_and_organs: 'Stimulates Kidney, Liver, and Urinary Bladder meridians.',
    joints: 'Hips and lower spine.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Bound Angle Pose.',
    other_notes: 'This pose helps open the hips for meditation.'
  },
  {
    title: 'Half Butterfly',
    benefits: 'Stretches one side of the lower back and inner thighs.',
    contraindications: 'Avoid if you have lumbar disc injuries.',
    into_pose: 'Extend one leg forward and bend the other foot to the inner thigh.',
    alternatives_and_options: 'Use a bolster under the bent knee.',
    out_of_pose: 'Support yourself back to a seated position.',
    counterposes: 'Cat-Cow Stretch.',
    meridians_and_organs: 'Kidney and Liver meridians.',
    joints: 'Hips and lower spine.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Janu Sirsasana.',
    other_notes: 'Focus on relaxing the spine as you fold.'
  },
  {
    title: 'Camel',
    benefits: 'Opens the chest, shoulders, and stretches the hip flexors.',
    contraindications: 'Avoid if you have severe neck or lower back pain.',
    into_pose: 'Kneel on the floor and lean back to place hands on heels.',
    alternatives_and_options: 'Place hands on blocks next to the feet for support.',
    out_of_pose: 'Slowly return to an upright kneeling position.',
    counterposes: 'Child’s Pose.',
    meridians_and_organs: 'Stimulates Heart and Lung meridians.',
    joints: 'Spine and shoulders.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Wheel Pose.',
    other_notes: 'Focus on opening the heart and avoiding lower back compression.'
  },
  {
    title: 'Cat Pulling Its Tail',
    benefits: 'Stretches the shoulders, spine, and hips.',
    contraindications: 'Avoid if you have wrist or knee injuries.',
    into_pose: 'On hands and knees, thread one arm through the other and pull the shoulder toward the floor.',
    alternatives_and_options: 'Place a bolster under the chest for more support.',
    out_of_pose: 'Return to all fours slowly.',
    counterposes: 'Child’s Pose.',
    meridians_and_organs: 'Stimulates the Gallbladder and Liver meridians.',
    joints: 'Shoulders, spine, and hips.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Thread the Needle Pose.',
    other_notes: 'Great for relieving tension in the upper back.'
  },
  {
    title: 'Caterpillar',
    benefits: 'Stretches the spine, hamstrings, and relieves lower back tension.',
    contraindications: 'Avoid if you have spinal disc issues.',
    into_pose: 'Sit with legs extended and slowly fold forward, bringing the chest toward the thighs.',
    alternatives_and_options: 'Place a cushion under the knees for support.',
    out_of_pose: 'Slowly uncurl the spine to return to seated position.',
    counterposes: 'Seated Twist.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Spine and hamstrings.',
    recommended_time: 'Three to five minutes.',
    similar_yang_asanas: 'Seated Forward Fold.',
    other_notes: 'Keep the spine long to avoid strain.'
  },
  {
    title: 'Child’s Pose',
    benefits: 'Gently stretches the back and hips, calming the nervous system.',
    contraindications: 'Avoid if you have knee injuries.',
    into_pose: 'Kneel and sit on the heels, then fold forward with arms extended.',
    alternatives_and_options: 'Place a cushion under the chest for added support.',
    out_of_pose: 'Slowly lift back up into kneeling position.',
    counterposes: 'Cat-Cow Stretch.',
    meridians_and_organs: 'Stimulates the Kidney meridians.',
    joints: 'Knees, hips, and spine.',
    recommended_time: 'Two to five minutes.',
    similar_yang_asanas: 'Balasana.',
    other_notes: 'Focus on releasing tension in the spine and pelvis.'
  },
  {
    title: 'Dangling',
    benefits: 'Relieves tension in the spine, neck, and hamstrings.',
    contraindications: 'Avoid if you have neck or lower back injuries.',
    into_pose: 'Stand with feet hip-width apart, then bend forward and let your head hang.',
    alternatives_and_options: 'Bend the knees slightly if hamstrings are tight.',
    out_of_pose: 'Slowly roll up one vertebra at a time.',
    counterposes: 'Standing Tall or Tadasana.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Spine and hips.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Forward Fold.',
    other_notes: 'Keep the knees soft to avoid straining the lower back.'
  },
  {
    title: 'Deer Pose',
    benefits: 'Opens the hips and stretches the quadriceps.',
    contraindications: 'Avoid if you have knee or hip injuries.',
    into_pose: 'Sit with legs extended, then bend one knee and place the foot near the opposite hip.',
    alternatives_and_options: 'Use a cushion for support under the hip of the bent leg.',
    out_of_pose: 'Return to seated position and switch sides.',
    counterposes: 'Reclined Twist.',
    meridians_and_organs: 'Stimulates the Liver and Gallbladder meridians.',
    joints: 'Hips and knees.',
    recommended_time: 'Two to five minutes per side.',
    similar_yang_asanas: 'Lotus Pose.',
    other_notes: 'Helps improve hip flexibility and mobility.'
  },
  {
    title: 'Dragons',
    benefits: 'Deeply stretches the hips, quads, and hip flexors.',
    contraindications: 'Avoid if you have knee or hip injuries.',
    into_pose: 'Step one foot forward into a lunge, keeping the back leg extended.',
    alternatives_and_options: 'Place blocks under the hands for added stability.',
    out_of_pose: 'Slowly step back into a standing position.',
    counterposes: 'Child’s Pose.',
    meridians_and_organs: 'Stimulates the Liver, Spleen, and Kidney meridians.',
    joints: 'Hips, knees, and spine.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Lunge Pose.',
    other_notes: 'Hold each side to feel a deep stretch in the hip flexors.'
  },
  {
    title: 'Frog',
    benefits: 'Deeply stretches the inner thighs, groin, and hips.',
    contraindications: 'Avoid if you have knee issues or hip pain.',
    into_pose: 'Start on all fours, then widen the knees and bring the feet to face outward.',
    alternatives_and_options: 'Place cushions under the knees for comfort.',
    out_of_pose: 'Move back into Child’s Pose to relax.',
    counterposes: 'Child’s Pose or seated forward fold.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Hips, knees, and pelvis.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Wide-Legged Forward Fold.',
    other_notes: 'This is a very deep stretch; use props to make it more accessible.'
  },
  {
    title: 'Happy Baby',
    benefits: 'Opens the hips and stretches the lower back.',
    contraindications: 'Avoid if you have neck or back issues.',
    into_pose: 'Lie on your back, grab the outside of your feet with your hands, and bring your knees toward your armpits.',
    alternatives_and_options: "Use a strap around the feet if you can't reach them.",
    out_of_pose: 'Release the feet and return to a lying position.',
    counterposes: 'Supta Baddha Konasana.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, spine, and knees.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Supta Padangusthasana.',
    other_notes: 'Focus on relaxing the neck and shoulders.'
  },
  {
    title: 'Reclining Twist',
    benefits: 'Relieves tension in the back and spine.',
    contraindications: 'Avoid if you have spinal issues or disc herniation.',
    into_pose: 'Lie on your back with knees bent, then slowly drop them to one side while turning your head in the opposite direction.',
    alternatives_and_options: 'Use a bolster under the knees for added support.',
    out_of_pose: 'Return to center and repeat on the other side.',
    counterposes: 'Savasana.',
    meridians_and_organs: 'Stimulates the Spleen and Stomach meridians.',
    joints: 'Spine and hips.',
    recommended_time: 'One to three minutes per side.',
    similar_yang_asanas: 'Seated Spinal Twist.',
    other_notes: 'Keep the shoulders grounded to deepen the twist.'
  },
  {
    title: 'Saddle',
    benefits: 'Opens the front of the hips and stretches the thighs.',
    contraindications: 'Avoid if you have knee or hip injuries.',
    into_pose: 'Kneel with knees wide apart, then lower your hips toward the floor and lie back on your forearms.',
    alternatives_and_options: 'Place cushions under the back for support if needed.',
    out_of_pose: 'Slowly sit up and return to a kneeling position.',
    counterposes: 'Child’s Pose.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, knees, and spine.',
    recommended_time: 'Two to three minutes.',
    similar_yang_asanas: 'Camel Pose.',
    other_notes: 'This is an intense hip opener, so use props for support.'
  },
  {
    title: 'Shavasana',
    benefits: 'Calms the body and mind, reduces stress, and improves relaxation.',
    contraindications: 'None unless you have severe back issues.',
    into_pose: 'Lie on your back with arms at your sides, palms facing up. Close your eyes and focus on deep breathing.',
    alternatives_and_options: 'Use a bolster under the knees for added comfort if you have lower back pain.',
    out_of_pose: 'Slowly awaken the body by gently moving the fingers and toes.',
    counterposes: 'None needed, as this is a final resting pose.',
    meridians_and_organs: 'Stimulates the entire body, allowing the nervous system to relax.',
    joints: 'Entire body.',
    recommended_time: 'Five to ten minutes.',
    similar_yang_asanas: 'None.',
    other_notes: 'Focus on the breath and let go of all tension.'
  },
  {
    title: 'Shoelace',
    benefits: 'Stretches the hips and glutes while relieving tension in the lower back.',
    contraindications: 'Avoid if you have knee injuries or severe hip pain.',
    into_pose: 'Sit with your legs crossed and stack one knee on top of the other, bringing the feet to the sides of the body.',
    alternatives_and_options: 'Place a cushion under the hips for added comfort.',
    out_of_pose: 'Slowly uncross the legs and extend them forward.',
    counterposes: 'Seated Forward Fold.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, knees, and lower back.',
    recommended_time: 'One to three minutes per side.',
    similar_yang_asanas: 'Fire Log Pose.',
    other_notes: 'This is a deep stretch for the hips, so move slowly into it.'
  },
  {
    title: 'Snail',
    benefits: 'Stimulates the nervous system and improves circulation to the head.',
    contraindications: 'Avoid if you have neck or back injuries.',
    into_pose: 'Lie on your back and bring the legs over the head to the floor, using your arms to support the back.',
    alternatives_and_options: 'Use a block or cushion under the feet for added support.',
    out_of_pose: 'Slowly roll back to a seated position.',
    counterposes: 'Child’s Pose.',
    meridians_and_organs: 'Stimulates the thyroid and nervous system.',
    joints: 'Spine and neck.',
    recommended_time: 'One to two minutes.',
    similar_yang_asanas: 'Plow Pose.',
    other_notes: 'This is an inversion, so proceed with caution.'
  },
  {
    title: 'Sphinx and Seal',
    benefits: 'Opens the chest and improves spinal flexibility.',
    contraindications: 'Avoid if you have severe lower back pain.',
    into_pose: 'Lie on your stomach, prop yourself up on your elbows for Sphinx Pose, and press into the hands to deepen the backbend for Seal Pose.',
    alternatives_and_options: 'Use a cushion under the pelvis if you have back discomfort.',
    out_of_pose: 'Slowly lower the torso to the floor.',
    counterposes: 'Child’s Pose or Downward Dog.',
    meridians_and_organs: 'Stimulates the Heart and Lung meridians.',
    joints: 'Spine and shoulders.',
    recommended_time: 'Two to three minutes.',
    similar_yang_asanas: 'Cobra Pose.',
    other_notes: 'Ensure you’re not overextending your lower back.'
  },
  {
    title: 'Square',
    benefits: 'Opens the hips and relieves tension in the lower back.',
    contraindications: 'Avoid if you have knee or hip issues.',
    into_pose: 'Sit with one leg bent in front and the other stacked on top, feet flexed and knees pointing out to the sides.',
    alternatives_and_options: 'Use cushions under the knees for support.',
    out_of_pose: 'Uncross the legs and return to a seated position.',
    counterposes: 'Child’s Pose.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Hips and knees.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Seated Forward Fold.',
    other_notes: 'Keep the spine long while folding forward.'
  },
  {
    title: 'Squat',
    benefits: 'Stretches the hips, groin, and ankles.',
    contraindications: 'Avoid if you have knee or hip issues.',
    into_pose: 'Squat with feet flat on the floor, keeping the chest lifted and hands in prayer position.',
    alternatives_and_options: 'Place a block under the hips for support if needed.',
    out_of_pose: 'Slowly rise back into a standing position.',
    counterposes: 'Forward Fold or Child’s Pose.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Hips, knees, and ankles.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Malasana.',
    other_notes: 'This pose is great for building strength and flexibility in the lower body.'
  },
  {
    title: 'Straddle (Dragonfly)',
    benefits: 'Stretches the inner thighs and hamstrings, improving flexibility in the spine.',
    contraindications: 'Avoid if you have hamstring injuries.',
    into_pose: 'Sit with legs extended wide apart, then slowly fold forward, reaching for your feet or the floor.',
    alternatives_and_options: 'Use blocks under the hands for support.',
    out_of_pose: 'Slowly come up from the fold and return to seated position.',
    counterposes: 'Seated Forward Fold.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Spine, hips, and hamstrings.',
    recommended_time: 'Two to four minutes.',
    similar_yang_asanas: 'Wide-Legged Forward Fold.',
    other_notes: 'Focus on lengthening the spine during the fold.'
  },
  {
    title: 'Swan & Sleeping Swan',
    benefits: 'Opens the hips and stretches the quads, releasing tension in the lower back.',
    contraindications: 'Avoid if you have knee or hip pain.',
    into_pose: 'From Downward Dog, bring one knee toward the chest and extend the opposite leg behind.',
    alternatives_and_options: 'Use props under the hips for support.',
    out_of_pose: 'Slowly transition back to Child’s Pose.',
    counterposes: 'Child’s Pose or Downward Dog.',
    meridians_and_organs: 'Stimulates the Liver and Kidney meridians.',
    joints: 'Hips and spine.',
    recommended_time: 'Two to three minutes per side.',
    similar_yang_asanas: 'Pigeon Pose.',
    other_notes: 'This is a deep hip opener that should be approached with care.'
  },
  {
    title: 'Toe Squat',
    benefits: 'Stretches the feet, ankles, and shins.',
    contraindications: 'Avoid if you have ankle or knee injuries.',
    into_pose: 'Start kneeling, then tuck your toes under and sit back on your heels.',
    alternatives_and_options: 'Use a blanket under the knees for added support.',
    out_of_pose: 'Slowly release the feet and return to a seated position.',
    counterposes: 'Seated Forward Fold.',
    meridians_and_organs: 'Stimulates the Kidney and Bladder meridians.',
    joints: 'Ankles and knees.',
    recommended_time: 'One to three minutes.',
    similar_yang_asanas: 'Hero Pose.',
    other_notes: 'This pose can be intense for the feet, so proceed with caution.'
  }
]
